# Generated by Django 5.0.3 on 2024-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomRover', '0002_room_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
