# Generated by Django 5.0.3 on 2024-06-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomRover', '0003_room_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='picture',
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomRover.room')),
            ],
        ),
    ]
