# Generated by Django 5.0.3 on 2024-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomRover', '0004_remove_room_picture_alter_room_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_pictures/'),
        ),
    ]
