# Generated by Django 5.0.3 on 2024-06-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomRover', '0005_alter_roomimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='size',
            new_name='other_facilities',
        ),
    ]
